### ISSUE TITLE
Able to change stack.data directly

### ISSUE THREAD

**Issue by eg-mart** [baitim/Stack#1]
I'm able to change stack's data directly (without calling the `stack_pop()` and `stack_push()` functions) in this commit: b5d8b63ca90d258a67e818d7c38b6c5583de8de8

For example, with this main function:
```cpp
int main()
{
    Stack stack = {};
   stack_ctor(&stack);

    stack_push(&stack, 1);
    stack.data[8] = 10;

    printf(type_el_print "\n", stack_pop(&stack));
    stack_dtor(&stack);
    
    return 0;
}
```
Code outputs 10, when it should output a dump of stack and abort/return an error.
I suspect that this code at Debug.cpp:121 might be at fault:
```cpp
int get_data_hash(Stack *stack)
{
    int size_struct = sizeof(long long) + sizeof(type_el *) + sizeof(int) * 2;
    return calculate_hash(stack, size_struct) + 
           calculate_hash(stack->data, sizeof(type_el) * stack->size);
}
```
For some reason, the hash is calculated based only on the `stack->size` first elements of stack.data, not based on all of stack.data. Left canary is not factored in too, for some reason.

Please, leave your thoughts on this here

**Comment by baitim** [comment]
Thank you for report, this bug fixxed
